# Generated by Django 5.0.7 on 2024-07-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_period',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
