# Generated by Django 5.0.6 on 2024-06-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('enrollment_date', models.DateField()),
                ('guardian_phone_number', models.CharField(max_length=15)),
                ('guardian_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('class_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_class.student_class')),
            ],
        ),
    ]
