# Generated by Django 5.0.7 on 2024-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(to="courses.course"),
        ),
    ]
