# Generated by Django 5.0.7 on 2024-08-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="course", new_name="courses",
        ),
    ]
